### ISSUE TITLE
My findings

### ISSUE THREAD

**Issue by NightHammer1000** [Creaous/Legion-Go-Resources#1]
Had the GO pretty much since it came out.

Here are a few Points I suggest:

**Change Emudeck to RetroBat**
EmuDeck is very steam centric. With its own Steam Steam Input Profiles. This will cause Issues with either Handheld Companion or Legion Space. Its also very messy with Sym and Hardlinks.
RetroBat can be installed completely contained on an SDCard for example. Everything in one Folder.

**Audio Loudness**
Instead of using Equilizer all up, Install FxSound or APO Equalizer and use the Preamp Feature.

**Some Games need a Keyboard connected**
In my Time with this Device I stumbled over this Issue multiple Times. Bioshock, Bioshock Remasterd, Mudrunner.
All these Games refuse to start without a Keyboard Device connected.
Solution for this is just to install https://tetherscript.com/controlmyjoystick-download/
No need to run it. Just install it.
Games will start after that.

**Comment by Creaous** [comment]
Thanks for your contribution, it has been added in 8840ea2 and 284e314.
