### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by DonutBling** [Creaous/Legion-Go-Resources#2]
v1.0.2.9

https://s3.service.lenovo.com/legion/cms/v24.04.09.01/legionspace.exe

 v1.1.2.11

https://s3.service.lenovo.com/legion/cms/v24.06.26.01/legionspace.exe

**Comment by Creaous** [comment]
Thank you for letting me know, I have added them now. I'll archive them when I get the chance to.

**Comment by DonutBling** [comment]
Thank you for providing this repository.  It's because of your notes that I was able to figure out these links based on their release window.  Also, I believe that the last two digits refer to the release number made on that day, like if they need to post a revision on the same day, so they'll probably all mostly end in 01.
