### ISSUE TITLE
Legion Space Update 1.1.3.3 

### ISSUE THREAD

**Issue by SeeDborg** [Creaous/Legion-Go-Resources#4]
Hello !
Would it be possible to have the link to direct download the latest version of Legion Space ?
The auto update is not working for me...

**Comment by Creaous** [comment]
Hi,

I have fetched the new file which is available at https://s3.service.lenovo.com/legion/cms/v24.09.25.01/legionspace.exe on Lenovo's official download server.

Alternatively, it has also been uploaded to the archive website which is available here https://archive.creaous.net/lenovo/legion-space/v1.1.3.3/legionspace.exe.

Related commit: a6910bf9c5486aec46326ead63d3890fc6b6e25e
